# Generated by Django 5.2.7 on 2025-11-19 01:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trustbadge",
            old_name="awarded_at",
            new_name="created_at",
        ),
        migrations.RemoveField(
            model_name="trustbadge",
            name="profile",
        ),
        migrations.AddField(
            model_name="trustbadge",
            name="giver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="given_badges",
                to="base.profile",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="trustbadge",
            name="receiver",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="received_badges",
                to="base.profile",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="trustbadge",
            name="badge_name",
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name="trustbadge",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name="trustbadge",
            constraint=models.UniqueConstraint(
                fields=("giver", "receiver"), name="unique_giver_receiver_badge"
            ),
        ),
    ]
