# Generated by Django 5.2.7 on 2025-11-23 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_exchange"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="event_end_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="post",
            name="post_type",
            field=models.CharField(
                choices=[
                    ("offer", "Offer"),
                    ("borrow", "Borrow"),
                    ("skillshare", "Skill Share"),
                    ("event", "Event"),
                ],
                max_length=15,
            ),
        ),
    ]
